version: '3.3'
services:
    mysql:
        image: iq-mysql
        container_name: iqCommerce-mysql
        tty: true
        stdin_open: true
        ports:
            - "3601:3306"
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mysql
            - SUMMARY=Mysql
            - DESCRIPTION
            - APP_DATA=/opt/app-root/src
            - CONTAINER_SCRIPTS_PATH=/usr/share/container-scripts/mysql
        volumes:
            - type: bind
              source: ${MYSQL_DATA_FOLDER}
              target: /var/lib/mysql
